/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Home from "./components/Home";

import About from './components/About';
import Support from './components/Support';
import Schemes from './components/Schemes';
import Signup from './components/SignUp';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
function App() {
  return (
    <>
    <Router>
      <Routes>
        <Route path="/" element={<Home />} />
        <Route path="/about" element={<About />} />
        <Route path="/support" element={<Support />} />
        <Route path="/schemes" element={<Schemes />} />
        <Route path="/signup" element={<Signup />} />
      </Routes>  
    </Router>
    
    </>
  );
}

export default App;
